### ISSUE TITLE
Unable to locate e2convertrelion.py

### ISSUE THREAD

**Issue by heejongkim** [cryoem/eman2-jupyter#1]
Hello,

Thanks for developing and sharing awesome software.
I have some datasets I'd like to try but they are all in Relion so I would like to convert them to try e2gmm.
Unfortunately, I wasn't able to locate e2convertrelion.py as mentioned in https://blake.bcm.edu/emanwiki/EMAN2/e2gmm
Can you please enlighten me where I can find it or how I can appropriately convert it for e2gmm?

thank you so much.

best,
heejong

**Comment by g5v991x** [comment]
It is in the examples/ folder. You can add the folder to your PATH to use it. 
Of course, being in the examples folder means it is not as ready as other programs in the main pipeline. If you notice anything wrong please let me know.

**Comment by heejongkim** [comment]
Ah.
It's under eman2's examples folder.
Thank you so much for your help.

best,
heejong
